.PHONY: clean All

All:
	@echo "----------Building project:[ toolsForBSSR - Debug ]----------"
	@cd "toolsForBSSR" && "$(MAKE)" -f  "toolsForBSSR.mk"
clean:
	@echo "----------Cleaning project:[ toolsForBSSR - Debug ]----------"
	@cd "toolsForBSSR" && "$(MAKE)" -f  "toolsForBSSR.mk" clean
